blank_issues_enabled: false
contact_links:
  - name: Documentation CLIMERI
    url: https://climeri-france.fr/acces-plateforme/
    about: Please check the documentation here. If you have any questions, send them to the mailing list replication@listes.ipsl.fr
