name: ESPRI data request form / Demande de données ESPRI
description: Data request form for ESPRI users.
title: "[Data Request]"
labels: ["enahancement"]
projects: ["AtefBN/1"]
assignees:
  - AtefBN
body:
  - type: markdown
    attributes:
      value: |
        Please make sure the data requested is published on ESGF nodes. IPSL data is already all on disk, if you have issues accessing please file a support ticket instead. 
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true

  - type: dropdown
    id: project
    attributes:
      label: Project
      description: What project data do you need?
      options:
        - CMIP6
        - CMIP5
        - CORDEX
        - obs4MIPS
        - input4MIPS
      default: 0
    validations:
      required: true



  - type: textarea
    id: Model
    attributes:
      label: Model
      description: List of models comma separated (except IPSL models, already on disk!)
      placeholder: ACCESS-ESM2-5
      value: "ACCESS-ESM2-5,CNRM-ESM2-1,EC-Earth3"
    validations:
      required: true


  - type: textarea
    id: Experiment
    attributes:
      label: Experiment
      description: List of experiments comma separated
      placeholder: historical,ssp126,ssp245
      value: "historical,ssp126,ssp245"
    validations:
      required: true


  - type: textarea
    id: Variables
    attributes:
      label: Variables
      description: List of variables comma separated
      placeholder: tas,tasmin,tasmax
      value: "tas,tasmin,tasmax"
    validations:
      required: true



  - type: textarea
    id: Frequency
    attributes:
      label: Frenquency
      description: List of models comma separated
      placeholder: 3hr,day
      value: "3hr,day"
    validations:
      required: true


  - type: textarea
    id: Variant-label
    attributes:
      label: Variant
      description: List of variant labels
      placeholder: r1i1p1f1
      value: "r1i1p1f1,r2i1p1f1"
    validations:
      required: true
